name: 'Core3 Github Utils'
description: 'Utilities for Github Actions'
author: 'Wix.com'
inputs:
  util:
    required: true
    description: Which util to use
  files:
    required: false
    description: check-files-existence - comma separated file paths to check
  allow_failure:
    required: false
    description: check-files-existence - fail if file(s) don't exist
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: blue
