name: 'Core3 Github Utils'
description: 'Utilities for Github Actions'
author: 'Wix.com'
inputs:
  util:
    required: true
    description: Which util to use (check-files-existence | read-file | wcs-sanity)
  files:
    required: false
    description: check-files-existence - comma separated file paths to check
  allow_failure:
    required: false
    description: check-files-existence & read-file & wcs-sanity - fail if file(s) don't exist
  filepath:
    required: false
    description: read-file - Filepath to read
  trim:
    required: false
    description: read-file - Boolean
  url:
    required: false
    description: wcs-sanity - Required - URL for deployed wcs, for sanity
  check-string:
    required: false
    description: wcs-sanity - Optional - A string to check on the first simulation
  image:
    required: false
    description: wcs-sanity - Optional - save image as screenshot.png
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: blue
