name: 'Core3 Github Utils'
description: 'Utilities for Github Actions'
author: 'Wix.com'
inputs:
  util:
    required: true
    description: Which util to use (check-files-existence | read-file )
  files:
    required: false
    description: check-files-existence - comma separated file paths to check
  allow_failure:
    required: false
    description: check-files-existence & read-file - fail if file(s) don't exist
  filepath:
    required: false
    description: read-file - Filepath to read
  trim:
    required: false
    description: read-file - Boolean
  parse:
    required: false
    description: 'read-file - string: mocha-failure-report | json-array'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: blue
