name: tests
on: [push, pull_request]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
  ### below are just test cases ###
  check-files-existence:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Single file - exist
        uses: 'wixplosives/core3-github-utils@master'
        with:
          util: 'check-files-existence'
          files: src/main.ts
      - name: Multiple files - exist
        uses: 'wixplosives/core3-github-utils@master'
        with:
          util: 'check-files-existence'
          files: src/main.ts, src/check-files-existence.ts
